[tool.black]
line-length = 88
target-version = ['py310']  # поменяй на свою версию Python при желании

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
exclude = [
    ".venv",
    "venv",
    "__pycache__",
]

[tool.pytest.ini_options]
markers = [
    "smoke: mark a test as a smoke test"
]